Правдин Иван 6312
itsec-labs/dotnet-2 pull request #10
Opened 2022-05-10 12:17 UTC by prafdin

Телеграм бот

2022-05-10 14:23 UTC, kolyanch requested changes

2022-05-10 14:23 UTC, kolyanch commented on TelegramBotServer/Program.cs
> +            }
Перенести этот код в класс Startup. Явным образом создавать и нужно ли добавлять в DI-контейнер эту задачу?

2022-05-10 14:23 UTC, kolyanch commented on TelegramBotServer/Repository/DbEventRepository.cs
> +            if (dbContext is null || dbContext.Events is null)
Здесь и дальше в коде.
GetRequiredService обязательно вернет экземпляр класса UsersContext, иначе, если объекта нет, то будет исключение. dbContext не может быть null. Поэтому проверка на null не имеет смысла

2022-05-10 14:23 UTC, kolyanch commented on TelegramBotServer/Repository/DbSubscriberRepository.cs
> +        private ILogger<DbSubscriberRepository> _logger;
Удалить пустую строку. Пометить как readonly

2022-05-10 14:23 UTC, kolyanch commented on TelegramBotServer/Repository/DbSubscriberRepository.cs
> +            return dbContext?.Subscribers?.Find(id);
dbContext уже не null. Тут и ниже

2022-05-10 14:23 UTC, kolyanch commented on TelegramBotServer/Repository/XmlSubscriberRepository.cs
> +                return new List<Subscriber>();
Используйте оператор ??

2022-05-10 14:23 UTC, kolyanch commented on TelegramBotServer/Repository/XmlSubscriberRepository.cs
> +                _subs[(int)index] = newSub;
Зачем тут приведение типов?

2022-05-10 14:23 UTC, kolyanch commented on TelegramBotServer/Services/CommandHandlerService.cs
> +        private IEventRepository _eventRepository;
Пометить как readonly

2022-05-10 14:23 UTC, kolyanch commented on TelegramBotServer/Services/CommandHandlerService.cs
> +                    UserId = message.From is null ? message.Chat.Id : message.From.Id,
Используйте оператор ??

2022-05-10 14:23 UTC, kolyanch commented on TelegramBotServer/Services/EventWatcherHostedService.cs
> +        public Timer? _timer { get; set; }
Сделать все приватным и либо сделать полями, либо переименовать

2022-05-10 14:23 UTC, kolyanch commented on TelegramBotServer/Services/IStartupTask.cs
> +namespace TelegramBotServer
Неправильный namespace

2022-05-10 14:23 UTC, kolyanch commented on TelegramBotServer/Services/TelegramNotificationSenderService.cs
> +        public ISubscriberRepository _subscriberRepository { get; private set; }
Либо private readonly поля, либо переименовывать

2022-05-10 14:23 UTC, kolyanch commented on TelegramBotServer/Services/TelegramNotificationSenderService.cs
> +                    message = $"Your event {someEvent.Id} overdui is {Math.Abs(rest)} minutes";
*overdue

2022-05-10 14:23 UTC, kolyanch commented on TelegramBotServer/Repository/XmlSubscriberRepository.cs
> +            _subs?.Add(newSub);
В CommandHandlerService в данный метод передается объект, у которого выставлены только UserId и ChatId. В отличие от БД, которая вам автоматически может сгенерить нужный идентификатор, в данном случае идентификатор всегда будет равен 0 и у вас, начиная со второго пользователя, поведение сервера будет очень своеобразным. Точнее, скорей всего, второй пользователь сможет видеть все события первого пользователя. Добавить автогенерацию идентификаторов

2022-05-10 14:23 UTC, kolyanch commented on TelegramBotServer/Validators/SubscriberValidator.cs
> +        private IEnumerable<Event> _events;
readonly

2022-05-10 14:23 UTC, kolyanch commented on TelegramBotServer/Validators/SubscriberValidator.cs
> +                    if (!_events.Any(e => e.Id == eventId))
Заменить на вызов All

2022-05-11 15:55 UTC, kolyanch commented
Дополнительно, пока ещё не все замечания не исправлены: а зачем вы делаете inject в репозитории работы с базой данных IServiceProvider и каждый раз вызываете GetRequiredService<UsersContext>(). Почему не делаете inject сразу UsersContext?

2022-05-11 16:29 UTC, prafdin commented
> Дополнительно, пока ещё не все замечания исправлены: а зачем вы делаете inject в репозитории работы с базой данных IServiceProvider и каждый раз вызываете GetRequiredService(). Почему не делаете inject сразу UsersContext?

Репозитории у меня Singleton, а  UsersContext у меня приходит как Transient, если я делаю inject таким образом  (AddDbContext). Поэтому сохранить контекст я не могу в поле репозитория, вроде. Или я ошибаюсь ?

2022-05-13 09:07 UTC, prafdin commented on TelegramBotServer/Services/CommandHandlerService.cs
> +                    UserId = message.From is null ? message.Chat.Id : message.From.Id,
Не соображу как тут его впихнуть. 
У меня же берётся ещё Id от From, точно он тут нужен ?

2022-05-13 09:07 UTC, prafdin commented on TelegramBotServer/Services/CommandHandlerService.cs
> +                var senderId = message.From is null ? message.Chat.Id : message.From.Id;
Не соображу как тут его впихнуть. 
У меня же берётся ещё Id от From, точно он тут нужен ?

2022-05-13 12:31 UTC, kolyanch commented on TelegramBotServer/Services/CommandHandlerService.cs
> +                var senderId = message.From is null ? message.Chat.Id : message.From.Id;
```C#
message.From?.Id ?? message.Chat.Id
```

2022-05-14 07:28 UTC, kolyanch requested changes
Сделать code cleanup

2022-05-14 07:28 UTC, kolyanch commented on TelegramBotServer.Tests/ControllersTests/EventControllerTests.cs
> +        private readonly DateTime validDeadline;
Нарушение правил именования приватных полей

2022-05-14 07:28 UTC, kolyanch commented on TelegramBotServer.Tests/ControllersTests/SubscriberControllerTests.cs
> +        private readonly int[] eventsId = { 1, 2, 3 };
Нарушение правил именования приватных полей. Поле перенести вниз, после констант

2022-05-14 07:28 UTC, kolyanch commented on TelegramBotServer.Tests/ValidatorsTests/EventValidatorTests.cs
> +        private readonly DateTime invalidDeadline;
Нарушение правил именования приватных полей

2022-05-14 07:28 UTC, kolyanch commented on TelegramBotServer.Tests/ValidatorsTests/SubscriberValidatorTests.cs
> +        private readonly int[] eventsId = { 1, 2, 3 };
Нарушение правил именования приватных полей

2022-05-14 07:28 UTC, kolyanch commented on TelegramBotServer/Repository/DbEventRepository.cs
> +        readonly private ILogger<DbEventRepository> _logger;
private readonly

2022-05-14 07:28 UTC, kolyanch commented on TelegramBotServer/Repository/DbSubscriberRepository.cs
> +        readonly private ILogger<DbSubscriberRepository> _logger;
private readonly

2022-05-15 17:23 UTC, kolyanch approved these changes

2022-05-15 17:27 UTC, kolyanch commented
Можете переходите к клиенту. 2 варианта:
- отдельное приложение. В этом случае я закрываю этот PR
- дорабатываете ваш класс CommandHandlerService, добавляете команды по добавлению и изменению событий. Единым клиентом при этом будет Telegram. В этом случае PR останется открытым до завершения реализации клиента.

Какой вариант выберите?

2022-05-16 09:29 UTC, prafdin commented
> Можете переходить к клиенту. 2 варианта:
> 
> * отдельное приложение. В этом случае я закрываю этот PR
> * дорабатываете ваш класс CommandHandlerService, добавляете команды по добавлению и изменению событий. Единым клиентом при этом будет Telegram. В этом случае PR останется открытым до завершения реализации клиента.
> 
> Какой вариант выберите?

Второй вариант

2022-05-18 12:25 UTC, kolyanch requested changes
- Сделать описание проекта, добавить скриншоты в него. Описать процесс запуска
- Выбор даты события сейчас сделан неудобно, приходится долго листать числа. Можно ли предусмотреть вариант ввода от пользователя даты как строки/числа?

2022-05-18 12:25 UTC, kolyanch commented on TelegramBotServer/Services/CommandHandlerService.cs
> +
Удалить одну пустую строку

2022-05-18 12:25 UTC, kolyanch commented on TelegramBotServer/Services/CommandHandlerService.cs
> +                if (session is null || callbackQuery.Message is null || callbackData?.Data is null)
session не может быть равным null. Если в словаре не будет элемент с указанным ключом, то будет исключение.

2022-05-18 12:25 UTC, kolyanch commented on TelegramBotServer/Services/CommandHandlerService.cs
> +                if (callbackData?.Type == CallbackDataType.Plan)
callbackData не может быть равным null. Переделайте этот if в switch

2022-05-18 12:25 UTC, kolyanch commented on TelegramBotServer/Services/CommandHandlerService.cs
> +                            }
Переделайте в switch

2022-05-18 12:25 UTC, kolyanch commented on TelegramBotServer/Services/CommandHandlerService.cs
> +                        session.ViewedTime = DateTime.Now;
Используйте оператор ??=

2022-05-18 12:25 UTC, kolyanch commented on TelegramBotServer/Services/CommandHandlerService.cs
> +        static private async Task<Message> SendDayInlineKeyboard(ITelegramBotClient bot,
Тут и в следующем методе. 
Модификатор доступа всегда должен идти первым: private static

2022-05-18 12:25 UTC, kolyanch commented on TelegramBotServer/Services/EventWatcherHostedService.cs
> +        private INotificationSenderService _notificationSender { get; set; }
Нарушение правил именования свойств

2022-05-18 12:25 UTC, kolyanch commented on TelegramBotServer/Services/SessionsCleanerHostedService.cs
> +        private SubscriberSessions _sessions;
Пометить как readonly

2022-05-18 12:25 UTC, kolyanch commented on TelegramBotServer/Services/TelegramNotificationSenderService.cs
> +        private SubscriberSessions _sessions;
Удалить пустую строку. Пометить как readonly

2022-05-18 12:25 UTC, kolyanch commented on TelegramBotServer/Services/TelegramNotificationSenderService.cs
> +                        JsonSerializer.Serialize(new CallbackData { Type= CallbackDataType.Notification, Data = $"{60}" }))});
Какой тайный смысл в использовании интерполирования строк для числа? Почему это сразу не сделать строкой?

2022-05-18 12:25 UTC, kolyanch commented on TelegramBotServer/Services/TelegramNotificationSenderService.cs
> +                return;
Кроме закрывающей скобки все остальное тут не нужно

2022-05-18 21:16 UTC, prafdin commented
> * Сделать описание проекта, добавить скриншоты в него. Описать процесс запуска
> * Выбор даты события сейчас сделан неудобно, приходится долго листать числа. Можно ли предусмотреть вариант ввода от пользователя даты как строки/числа?

От считывания даты в сыром виде отказался по той причине, что либо пользователя жестко фиксируем в формате ввода, либо приходиться мучиться с парсером. В качестве утешения добавил выбор месяца.

2022-05-19 03:34 UTC, kolyanch requested changes

2022-05-19 03:34 UTC, kolyanch commented on TelegramBotServer/Services/EventWatcherHostedService.cs
> +        private INotificationSenderService _notificationSender;
readonly

2022-05-21 13:50 UTC, kolyanch approved these changes

2022-05-21 13:52 UTC, kolyanch commented
Для сдачи приготовьте небольшую демонстрацию проекта

2022-05-21 13:52 UTC, closed without merging