Telegram Bot Client
itsec-labs/dotnet-2 pull request #12
Opened 2022-05-19 09:31 UTC by putilove

Путилов Глеб 6312

2022-05-19 12:02 UTC, kolyanch requested changes

2022-05-19 12:02 UTC, kolyanch commented on src/Server/Client/ViewModels/EventViewModel.cs
> +            }
Используйте валидацию на уровне пользовательского интерфейсах

2022-05-19 19:07 UTC, putilove commented on src/Server/Client/FodyWeavers.xml
> +﻿<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
Файл генерится сам с пакетом ReactiveUI.Fody, от этого пакета зависит Reactive

2022-05-24 16:05 UTC, putilove commented
Я возможно ветки загадил себе

2022-05-24 16:23 UTC, kolyanch requested changes

2022-05-24 16:23 UTC, kolyanch commented on src/Server/Client/EventWindow.xaml
> +        <Style x:Key="Date">
x:Key в данном случае не нужен

2022-05-24 16:23 UTC, kolyanch commented on src/Server/Client/ValidationRules/DateValidationRule.cs
> +            return (!string.IsNullOrWhiteSpace(val) && !string.IsNullOrEmpty(val) && DateTime.TryParse(val, out var _))
- IsNullOrWhiteSpace покрывает проверку IsNullOrEmpty, поэтому IsNullOrEmpty не нужно проверять
- var после out не нужен
- общие круглые скобки также не нужны

2022-05-24 16:23 UTC, kolyanch commented on src/Server/Client/ValidationRules/EventFrequencyValidationRule.cs
> +            return (!string.IsNullOrWhiteSpace(val) && !string.IsNullOrEmpty(val) && int.TryParse(val, out var data) && data > 0 && data < 8)
1. Аналогично классу DateValidationRule не нужно проверять IsNullOrEmpty
2. ```data is > 0 and < 8```

2022-05-24 16:23 UTC, kolyanch commented on src/Server/Client/ValidationRules/EventNameValidationRule.cs
> +            return (!string.IsNullOrWhiteSpace(val) && !string.IsNullOrEmpty(val))
Аналогично ненужная проверка на IsNullOrEmpty

2022-05-24 18:26 UTC, kolyanch approved these changes

2022-05-24 18:26 UTC, kolyanch commented
Для сдачи приготовьте небольшую демонстрацию проекта

2022-05-24 18:26 UTC, closed without merging