Order Accounting System
itsec-labs/dotnet-2 pull request #13
Opened 2022-05-20 16:38 UTC by Sorokina6312

Сорокина Кристина 6312

2022-05-21 07:35 UTC, kolyanch requested changes
Сделать code cleanup

2022-05-21 07:35 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Models/Customer.cs
> +    /// <summary>Info about customer</summary>
Данный xml-комментарий сделан неверно. Комментирование должно осуществляться до всех аттрибутов. Аналогично в других классах.

2022-05-21 07:35 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Models/Customer.cs
> +namespace OrderAccountingSystem.Model
Неправильный namespace

2022-05-21 07:35 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Repository/CustomerRepository.cs
> +namespace OrderAccountingSystem.Repositories
Неправильный namespace

2022-05-21 07:35 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Repository/CustomerRepository.cs
> +        private static SemaphoreSlim SemaphoreSlim = new SemaphoreSlim(1, 1);
readonly

2022-05-21 07:35 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Repository/CustomerRepository.cs
> +        private readonly string _fileName = "Customers.xml";
Имя файла необходимо читать из настроек проекта

2022-05-21 07:35 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Repository/CustomerRepository.cs
> +                throw new ArgumentException();
В конструктор исключения необходимо передать параметр

2022-05-21 07:35 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Repository/CustomerRepository.cs
> +                FileStream fs = new FileStream(_fileName, FileMode.OpenOrCreate);
Переменную fs переименовать. Учесть, что FileStream реализует IDisposable. Аналогично в методе Write

2022-05-21 07:35 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Repository/CustomerRepository.cs
> +}
Замечания для данного класса справедливы для всех остальных репозиториев

2022-05-21 07:35 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Repository/ICustomerRepository.cs
> +namespace OrderAccountingSystem.Repositories
Сделать выверку пространств имен во всех файлах

2022-05-21 07:35 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Repository/IOrderRepository.cs
> +        Task WriteOrdersFileAsync();
Зачем эти методы в интерфейсе? Аналогично для остальных репозиториев

2022-05-21 07:35 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Services/AccountingSystemService.cs
> +                }); ;
Зачем тут две точки с запятой?

2022-05-21 07:35 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Services/AccountingSystemService.cs
> +            return Guid.TryParse(value, out x);
Использовать _

2022-05-21 13:42 UTC, kolyanch requested changes
На данный момент не срабатывает ни один тест

2022-05-21 13:42 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Repository/CustomerRepository.cs
> +        private readonly static SemaphoreSlim SemaphoreSlim = new SemaphoreSlim(1, 1);
private static readonly. И так во всех репозиториях

2022-05-21 13:42 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Repository/CustomerRepository.cs
> +                fileStream.Dispose();
Переделать на using

2022-05-21 13:42 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Repository/CustomerRepository.cs
> +                fileStream.Dispose();
Переделать на using

2022-05-21 13:42 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Services/AccountingSystemService.cs
> +            return Guid.TryParse(value, out _x);
Использовать _ (discard parameter)

2022-05-22 15:49 UTC, kolyanch requested changes

2022-05-22 15:49 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Repository/CustomerRepository.cs
> +                using FileStream fileStream = new FileStream(_fileName, FileMode.OpenOrCreate);
await using тут и дальше

2022-05-22 15:49 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Repository/CustomerRepository.cs
> +        public async Task ReadCustomersFileAsync()
Методы недоступные через интерфейс сделать приватными во всех репозиториях

2022-05-22 15:49 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystem/Services/AccountingSystemService.cs
> +namespace OrderAccountingSystem
Неверный namespace

2022-05-22 15:49 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystemTests/CustomerRepositoryTest.cs
> +        private static readonly IConfigurationRoot _config = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
Удалить ненужную пустую строку. Нарушение правил именования приватного статичного поля. Так во всех тестах

2022-05-22 17:48 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystemTests/CustomerRepositoryTest.cs
> +        private static readonly IConfigurationRoot _config = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
Не исправлено

2022-05-23 16:08 UTC, Sorokina6312 commented on OrderAccountingSystem/OrderAccountingSystemTests/CustomerRepositoryTest.cs
> +        private static readonly IConfigurationRoot _config = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
Онон исправлено, но тут, почему-то, не отобразилось. Ели смотреть через просто через папку проекта, то там видно, что исправлено(
![image](https://user-images.githubusercontent.com/92379489/169861617-d35f5afb-e8fa-4944-a7f3-e0acfb57dc98.png)

2022-05-23 16:38 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystemTests/CustomerRepositoryTest.cs
> +        private static readonly IConfigurationRoot _config = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
Название переменной должно быть Config, она static

2022-05-23 18:31 UTC, Sorokina6312 commented on OrderAccountingSystem/OrderAccountingSystemTests/CustomerRepositoryTest.cs
> +        private static readonly IConfigurationRoot _config = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
Поправила

2022-05-23 18:42 UTC, kolyanch commented on OrderAccountingSystem/OrderAccountingSystemTests/CustomerRepositoryTest.cs
> +        private static readonly IConfigurationRoot _config = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
![image](https://user-images.githubusercontent.com/73119715/169885622-86af9515-96ce-4794-8adb-65ff5af08c66.png)

Вы русскую букву С написали, нужно английскую

2022-05-24 06:24 UTC, Sorokina6312 commented on OrderAccountingSystem/OrderAccountingSystemTests/CustomerRepositoryTest.cs
> +        private static readonly IConfigurationRoot _config = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
Исправлено

2022-05-24 06:28 UTC, kolyanch approved these changes

2022-05-24 06:29 UTC, closed without merging