сервер чата (SignalR + JSON)
itsec-labs/dotnet-2 pull request #16
Opened 2022-05-23 19:01 UTC by EraserH

Сервер и тесты к сериализаторам (личные сообщения и сообщения в группах)

2022-05-24 04:34 UTC, kolyanch requested changes
- Сделать code cleanup
- Для групповых чатов не отработана ситуация, когда несколько пользователей будут одновременно писать сообщения. Тест для этого случая:
```C#
[Fact]
public void GroupMessageConcurrent()
{
    var tasks = new List<Task>();
    for (var i = 0; i < 10; i++)
    {
        var userName = $"user{i}";
        tasks.Add(Task.Run(() =>
        {
            GroupMessageSerializer.SerializeMessage(new GroupMessage("test", userName, $"Message from {userName}"));
        }));
    }

    Task.WaitAll(tasks.ToArray());
}
```

2022-05-24 04:34 UTC, kolyanch commented on ChatServer/Serializers/DirectMessageSerializer.cs
> +#pragma warning restore CS0659 // 'DirectMessage' overrides Object.Equals(object o) but does not override Object.GetHashCode()
Если вы подавляете warning, то в #pragma необходимо обернуть конкретный метод Equals

2022-05-24 04:34 UTC, kolyanch commented on ChatServer/Serializers/DirectMessageSerializer.cs
> +            return false;
Метод должен быть записан в 2 строки:
```C#
if (obj is not DirectMessage directMessage) return false;
return directMessage.Receiver == Receiver && directMessage.Name == Name && directMessage.Message == Message;
```

2022-05-24 04:34 UTC, kolyanch commented on ChatServer/Serializers/DirectMessageSerializer.cs
> +    public class DirectMessageSerializer
Класс вынести в отдельный файл. Пометить как static

2022-05-24 04:34 UTC, kolyanch commented on ChatServer/Serializers/GroupMessageSerializer.cs
> +            }*/
Удалить все закомментированные куски кода их этого файла

2022-05-24 04:34 UTC, kolyanch commented on ChatServer/Serializers/GroupMessageSerializer.cs
> +    public class GroupMessage
Замечания по этому классу идентичны классу DirectMessageSerializer

2022-05-24 04:34 UTC, kolyanch commented on ChatServer/Serializers/DirectMessageSerializer.cs
> +        public static List<DirectMessage> DeSerializeMessage(string receiverName)
*DeserializeMessage

2022-05-24 18:56 UTC, EraserH commented on ChatServer/Serializers/DirectMessageSerializer.cs
> +#pragma warning restore CS0659 // 'DirectMessage' overrides Object.Equals(object o) but does not override Object.GetHashCode()
а можно пояснить, как метод обернуть конкретный обернуть?

2022-05-24 19:16 UTC, kolyanch commented
Реализация конкретного доступа к файлу может быть сделана через блокировку (lock), либо логика сохранения может быть изменена. Вместо сохранения файла при каждом новом сообщении вы держите все сообщения в памяти и параллельной фоновой задачей сохраняете в файл на диск, например, раз в минуту. В первом случае по сути одновременных записей в файл не будет, но замедлится сохранение при большом количестве пользователей/сообщений. Во втором возрастёт объем потребляемой сервером оперативной памяти. Примеры обоих реализаций можете найти в уже закрытых PR.

2022-05-25 07:38 UTC, kolyanch requested changes
Сделать code cleanup во всем решении

2022-05-25 07:38 UTC, kolyanch commented on ChatServer/Serializers/GroupMessageSerializer.cs
> +            using (FileStream fs = new FileStream(fileName, FileMode.OpenOrCreate))
Используйте await using declaration:
```C#
await using var fs = new FileStream(fileName, FileMode.OpenOrCreate);
``` 

В методе ниже также.

2022-05-25 07:38 UTC, kolyanch commented on ChatServer/Serializers/GroupMessageSerializer.cs
> +            var deserializedMessages = new List<GroupMessage>();
Зачем вы тут создаете новый список, если ниже вы его инициализируете заново?

2022-05-25 07:58 UTC, closed without merging