Server Accounting System
itsec-labs/dotnet-2 pull request #2
Opened 2022-03-31 19:38 UTC by SirlLizz

Моисеев Илья 6312

2022-03-31 19:43 UTC, SirlLizz commented
И какие критерии для клиента вообще есть? Ну кроме полного раскрытия функционала сервера

2022-04-01 07:03 UTC, SirlLizz commented
И можно ли сразу делать pr на клиента паралельно со сдачей сервера?

2022-04-01 07:08 UTC, kolyanch requested changes
1. Во всех файлах удалить неиспользуемые using
2. В качестве фреймворка для unit-тестирования необходимо использовать xUnit
3. Покрыть тестами репозитории

2022-04-01 07:08 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Repository/CustomerRepository.cs
> +        private static ISession session = NHibernateSession.OpenSession();
Статические поля не нужно использовать в веб-проектах. Если хотите создать объект один раз, используйте Singleton. Либо создавайте сессию при каждом вызове методов.

Так во всех репозиториях.

2022-04-01 07:08 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Repository/OrderRepository.cs
> +            }
Используйте LINQ

2022-04-01 07:08 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Repository/OrderRepository.cs
> +}
Тут поехала разметка кода и дальше также

2022-04-01 07:08 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Repository/OrderRepository.cs
> +        public double calculationPrice(Order order)
Нарушение правил именования методов. Метод может быть переделан на private

2022-04-01 07:08 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Repository/OrderRepository.cs
> +            return price;
Весь метод нужно написать одной строкой с использованием LINQ

2022-04-01 07:08 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/CustomerControllerTests.cs
> +            //var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
Это либо удалить, либо отправить в новый тест

2022-04-01 07:08 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/CustomerControllerTests.cs
> +            //var content = new StringContent(JsonConvert.SerializeObject(model));
Идентично замечанию выше

2022-04-01 07:10 UTC, kolyanch commented
> А можно с клиентом не сильно заморачиваться, написать на голом js без использования фреймворков? А то в таком проекте даже реакт будет избытычен...

Можете делать на чистом HTML/JS/CSS

> И какие критерии для клиента вообще есть? Ну кроме полного раскрытия функционала сервера

Удобный UI, общая работоспособность

> И можно ли сразу делать pr на клиента паралельно со сдачей сервера?

Советую сначала доделать PR по серверу

2022-04-01 07:42 UTC, SirlLizz commented
Просто я еще думал добавить xslt взаимодействие в проект. И, конечно же, сохранение и загрузку данных в бд и из бд с валидацией xsd или dtd, но пока не знаю как на шарпе это делается. Можно это будет добавить чуть попозже и будет ли это оценено в доп.баллы?

2022-04-01 07:44 UTC, SirlLizz commented on src/AccountingSystem/TestServerAccountingSystem/CustomerControllerTests.cs
> +            //var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
Это я хотел спросит, какой из вариантов создания responce лучше оставить, я просто разными попробовал

2022-04-01 07:54 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/CustomerControllerTests.cs
> +            //var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
Это не response, это тело реквеста. Так как сейчас пойдет, но лучше \" используйте. Json-ы для тестов также можете читать из файла. 

Если тесты будут однообразные как сейчас, то рекомендуется использовать Theory

2022-04-01 08:04 UTC, kolyanch commented
> Просто я еще думал добавить xslt взаимодействие в проект. И, конечно же, сохранение и загрузку данных в бд и из бд с валидацией xsd или dtd, но пока не знаю как на шарпе это делается. Можно это будет добавить чуть попозже и будет ли это оценено в доп.баллы?

Если вы делаете проект с использованием БД, то xml вам вообще не нужен. dtd - ужасная устаревшая дичь, небезопасная и страшная, забудьте о ней. Xslt вам тоже вряд ли пригодится

2022-04-01 08:07 UTC, SirlLizz commented
Ну просто думал добавить возможность переноса с одного сервера данных на другой посредством xml, но тогда хорошо, не буду

2022-04-01 08:08 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Repository/CustomerRepository.cs
> +        private static ISession session = NHibernateSession.OpenSession();
Если он хранит в себе какие-то данные, то они должны быть потокобезопасными. Но лучше использовать кратковременные сессии для каждого запроса. Если у вас REST-сервис, то все классы и методы контроллеров должны быть stateless - ни один метод не должен зависить от другого и не шарить ни какие данные.

2022-04-01 08:08 UTC, SirlLizz commented
> > Просто я еще думал добавить xslt взаимодействие в проект. И, конечно же, сохранение и загрузку данных в бд и из бд с валидацией xsd или dtd, но пока не знаю как на шарпе это делается. Можно это будет добавить чуть попозже и будет ли это оценено в доп.баллы?
> 
> Если вы делаете проект с использованием БД, то xml вам вообще не нужен. dtd - ужасная устаревшая дичь, небезопасная и страшная, забудьте о ней. Xslt вам тоже вряд ли пригодится

Но xsd же вроде даже в коммерческих проектах используется

2022-04-01 08:11 UTC, kolyanch commented
Xsd используется практически всегда, когда есть xml. К чему может приводить DTD и как делать xml-бомбы можете почитать тут, например: https://dahiya-aj.medium.com/what-is-xml-injection-attack-279691bd00b6

2022-04-01 13:07 UTC, SirlLizz commented
Можно, пожалуйста, повторный ревью?

2022-04-02 08:30 UTC, kolyanch requested changes

2022-04-02 08:30 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Connection/NHibernateSession.cs
> +        readonly static ISessionFactory Factory = CreateSessionFactory();
Переставить модификаторы: static readonly.
Явно указать private

2022-04-02 08:30 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Controllers/CustomerController.cs
> +        ICustomerRepository _repository;
Явно указать private readonly

2022-04-02 08:30 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Controllers/OrderController.cs
> +        [HttpPatch("status-{id:int}")]
Почему такой странный маршрут? Чем принципиально отличается от Put?

2022-04-02 08:30 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Repository/OrderRepository.cs
> +        private double calculationPrice(Order order)
Нарушение правил именования методов

2022-04-02 08:30 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/CustomerControllerTests.cs
> +        [Theory]
Вы не поняли смысл теории. Применяется, если один и тот же тест запускается несколько раз с разными данными. В данном случае подходит факт. Либо измените аргумент и выполняйте тестирование на наборе данных

2022-04-02 08:30 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/CustomerRepositoryTests.cs
> +            customer.Address = "SPB";
В таких случаях лучше использовать инициализатор:
```C#
var customer = new Customer
{
    CustomerId = 57,
    Name = "Vova",
    Phone = "888",
    Address = "SPB"
};
```

2022-04-02 08:30 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/OrderControllerTests.cs
> +            HttpResponseMessage response = await httpClient.PutAsync(url, content);
Разве тут должен быть Put?

2022-04-02 16:01 UTC, SirlLizz commented on src/AccountingSystem/AccountingSystem/Controllers/OrderController.cs
> +        [HttpPatch("status-{id:int}")]
В том, что изменяется только поле статус. Такой путь сделал на тот случай, если вдруг решу делать изменение еще каких-либо полей

2022-04-02 17:11 UTC, SirlLizz commented
Можно повторный ревью?

2022-04-02 19:55 UTC, SirlLizz commented
И еще такой вопрос - начал смотреть по клиенту и задался вопросом - а можно как-то подключить чистый html? А то где не читаю, везде на cshtml. Да, я понимаю, что это по факту тоже самое, но все же интересно стало, реально ли

2022-04-03 09:08 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Controllers/OrderController.cs
> +        [HttpPatch("status-{id:int}")]
Так не нужно делать. Даже если у вас к изменению доступно только поле статуса, то необходимо обеспечить у метода Patch сигнатуру идентичную методу Put. int передавать в теле запроса смысла нет. Метод должен принимать Order в теле или data transformation object (DTO) на его основе, содержащий поле со статусом.

2022-04-03 09:21 UTC, kolyanch requested changes
Дополнительные замечания:
1. Для всех контроллеров и репозиториев - изменить возвращаемые типы методов. Сейчас возвращается 1 или 0, что не верно. К примеру метод POST и соответствующий метод репозитория должен вернуть идентификатор объекта, чтобы клиент мог корректно с ним работать. 
2. Для тестов сменить работу с теориями, параметризация урлом плохо выглядит. Дополнительно - каким образом в тест-методах изменения объектов гарантируется, что в БД присутствуют записи с такими идентификаторами.

2022-04-03 09:21 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Connection/NHibernateSession.cs
> +    public class NHibernateSession
Если в классе все методы статические, то и класс стоит пометить как статический

2022-04-03 09:21 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/CustomerControllerTests.cs
> +        [InlineData("api/Customer/1")]
Зачем параметризировать таким образом?
Почему не сделать параметром идентификатор?

2022-04-03 09:21 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Repository/OrderRepository.cs
> +        private double СalculationPrice(Order order)
Опечатка, даже гитхаб подсвечивает

2022-04-03 09:42 UTC, kolyanch commented
> И еще такой вопрос - начал смотреть по клиенту и задался вопросом - а можно как-то подключить чистый html? А то где не читаю, везде на cshtml. Да, я понимаю, что это по факту тоже самое, но все же интересно стало, реально ли

Подключить куда? Если вы хотите сделать клиентское приложение на чистом html/js/css, то вам все равно понадобится некоторое подобие веб-сервера для отладки, создания модулей и последующей минификации. Проект клиента у вас при этом будет просто как папка. Посмотрите в сторону webpack

2022-04-03 10:41 UTC, SirlLizz commented
Исправил, можно повторный ревью?

2022-04-03 11:24 UTC, kolyanch commented
- Не исправлен PATCH в OrderController
- Возвращаемые значения во всех actions контроллеров могут вводить в заблуждение. -1 вполне себе нормальный идентификатор для ресурса. У вас же получается, что при любой некорректной ситуации вернется -1. Это нарушение REST API. Для возврата кода существует понятие response status code: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status . Используйте методы контроллера для возврата нужного кода - NotFound, Problem, Ok и т.д.
- Тесты до сих пор вызывают вопросы. С учетом того, что все они могут быть запущены параллельно, что если RemoveProduct, например, вызовется раньше чем ChangeProduct?
- Код клиентского приложения должен быть в отдельном проекте/папке
- OpenAPI описание на данный момент отсутствует. Добавьте комментарии ко всем используемым ресурсам и методам

2022-04-03 12:00 UTC, SirlLizz commented
> * OpenAPI описание на данный момент отсутствует. Добавьте комментарии ко всем используемым ресурсам и методам
А куда добавить эти комментарии?

2022-04-03 12:05 UTC, kolyanch commented
> > * OpenAPI описание на данный момент отсутствует. Добавьте комментарии ко всем используемым ресурсам и методам
> 
> А куда добавить эти комментарии?

https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-6.0&tabs=visual-studio#xml-comments

2022-04-03 12:32 UTC, SirlLizz commented
> * Возвращаемые значения во всех actions контроллеров могут вводить в заблуждение. -1 вполне себе нормальный идентификатор для ресурса. У вас же получается, что при любой некорректной ситуации вернется -1. Это нарушение REST API. Для возврата кода существует понятие response status code: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status . Используйте методы контроллера для возврата нужного кода - NotFound, Problem, Ok и т.д.


А если статус код будет перекликаться с id объекта? Я как понял, если у нас все нормально, то мы возвращаем id объекта, если вылетел exeption, то возвращаем како-то из статус кодов. 
Типо такого:
 public int PatchStatus(int status, Order order)
        {
            try
            {
                ISession session = NHibernateSession.OpenSession();
                using (session.BeginTransaction())
                {
                    order.Status = status;
                    session.Save(order);
                    session.GetCurrentTransaction().Commit();
                }
                return order.OrderId;
            }
            catch (NullReferenceException)
            {
                return 500;
            }
        }

Или вот так:
 public HttpStatusCode PatchStatus(int status, Order order)
        {
            try
            {
                ISession session = NHibernateSession.OpenSession();
                using (session.BeginTransaction())
                {
                    order.Status = status;
                    session.Save(order);
                    session.GetCurrentTransaction().Commit();
                }
                return HttpStatusCode.OK;
            }
            catch (NullReferenceException)
            {
                return HttpStatusCode.NotFound;
            }
        }

2022-04-03 16:03 UTC, kolyanch commented
> 

В репозиторие так делать нельзя. Он ничего не должен знать о http status code и прочем. Он не должен зависить от конкретики реализации API. Про статус коды могут знать только actions внутри контроллеров. Ни один из вариантов приведенных выше не подходит

2022-04-05 09:25 UTC, SirlLizz commented
Исправил вроде все, но так и не придумал, что можно сделать с юнит тестами

2022-04-05 13:11 UTC, kolyanch commented
Пока мало что поменялось:
- Не исправлен PATCH в OrderController. Он должен иметь сигнатуру:
```C#
public ActionResult<int> PatchStatus(int id, [FromBody] Order order)
```
Из объекта order вы можете брать только статус и обновлять по нему. Если задаты другие свойства, выдавать исключение или просто игнорировать их. Либо сделать отдельный DTO для этого случая.
- Возврат Confict() вообще не применим в данном случае. Что, если в приложении просто задана строка соединения с несуществующей БД? Что, если объект заданным идентификатором не найден? Что, если просто произошла какая-то ошибка? Должны быть обработаны конкретные виды исключений. В репозитории можете также кидать исключения при определенных ситуациях.
- Комментарии в коде не зарегистрированы для OpenAPI описания. Также отсутствуют комментарии для ресурсов - классов вашей модели данных.
- Тестирование можете делать с использованием Fixture: https://xunit.net/docs/shared-context

2022-04-05 18:36 UTC, SirlLizz commented
Можно повторный ревью?

2022-04-06 05:55 UTC, kolyanch requested changes

2022-04-06 05:55 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Controllers/CustomerController.cs
> +        [ProducesResponseType(StatusCodes.Status403Forbidden)]
Почему только у этого метода задан аттрибут?
Почему именно Forbidden?

Для всех контроллеров

2022-04-06 05:55 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Controllers/CustomerController.cs
> +            catch (NullReferenceException)
NullReferenceException заменить на другой вид исключения. В данном случае возможно лучше создать свой класс исключения, генерировать его в методах репозитория, в случае, если объект не найден в БД. Так для всех методов всех контроллеров

2022-04-06 05:55 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Controllers/CustomerController.cs
> +                return Forbid();
Forbid может применяться только в случаях, если в приложении присутствует авторизация. Описание кода: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

У вас же получается, что даже, если БД не существует, будет forbidden. Используйте метод Problem.
Так для всех методов всех контроллеров

2022-04-06 05:55 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Controllers/CustomerController.cs
> +                return Conflict();
В чем тут конфликт?

2022-04-06 05:55 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Controllers/OrderController.cs
> +        [HttpPatch("status-{id:int}")]
Переименовать в просто Patch

2022-04-06 05:55 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Model/Order.cs
> +    public class Order
В классе отсутствует дата заказа. 
Из задания: вывод отчета за месяц - самые продающиеся продукты и их суммарная стоимость.

Исходя из этого модифицировать репозиторий

2022-04-06 05:55 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/CustomerControllerTests.cs
> +            httpClient.PostAsync("api/Customer", content);
Так нельзя. Получается вы не тестируете метод Post и Delete. Аналогично во все тест-классах

2022-04-06 06:10 UTC, SirlLizz commented on src/AccountingSystem/AccountingSystem/Controllers/CustomerController.cs
> +        [ProducesResponseType(StatusCodes.Status403Forbidden)]
Потому что лист customerов нельзя засунуть в дженерик ActionResult, поэтому и решил в случае неплановой ситуации, которая тут может быть только в случае не соединения с бд, возвращать статус код с указания атрибута

2022-04-06 06:14 UTC, SirlLizz commented on src/AccountingSystem/AccountingSystem/Controllers/CustomerController.cs
> +                return Conflict();
Если в базу данных не смогут вставится данные

2022-04-06 07:47 UTC, SirlLizz commented on src/AccountingSystem/AccountingSystem/Controllers/CustomerController.cs
> +                return Conflict();
А вот NoFound надо убрать

2022-04-06 07:59 UTC, SirlLizz commented on src/AccountingSystem/AccountingSystem/Controllers/CustomerController.cs
> +        [ProducesResponseType(StatusCodes.Status403Forbidden)]
Получается только так

2022-04-06 07:59 UTC, SirlLizz commented on src/AccountingSystem/AccountingSystem/Controllers/CustomerController.cs
> +        [ProducesResponseType(StatusCodes.Status403Forbidden)]
[HttpGet]
public ActionResult<IList<Product>> Get()
{
    return _repository.GetProducts().ToList();
}

2022-04-06 08:53 UTC, SirlLizz commented on src/AccountingSystem/AccountingSystem/Model/Order.cs
> +    public class Order
Так я не смогу реализовать самые продающиеся продукты, потому что сделал систему учета заказов, то есть у меня один продукт - один заказ(как в сервисных центрах). Можно просто сделать количество проданных заказов за последний месяц, иначе придется вообще всю систему взаимодействия с бд менять

2022-04-06 11:13 UTC, SirlLizz commented
Посмотрите, пожалуйста, еще раз

2022-04-06 15:36 UTC, kolyanch requested changes
Немного замечаний, уже лучше.

По тестам все по прежнему не верно.
Fixture - общий контекст для всех тестов в рамках одного класса.
В рамках этого класса вы должны воссоздать структуру базы данных, на которой вы будете выполнять тестирование и возможно наполнить её данными. Это делается для того, чтобы тестирование можно было произвести в том числе:
- на компьютере, у которого нет доступа к БД, которая используется при разработке
- в рамках CI/CD сценариев.
Понадобится вам скорее даже ICollectionFixture, так как все тесты будут работать с одной БД.

Тестирование репозитория:
При выполнении тестов на Get никаких дополнительных действий производить не нужно.
При выполнении Insert/Add производите добавление в бд, после проверяете, что запись добавлена, например прямым SQL-запросом, потом удаляете вставленную запись. Тем самым возвращаете БД в изначальное состояние.
При тестировании Delete, вставляете в БД произвольную новую запись, удаляете её, проверяете, что она действительно удалилась, например, проверяя количество записей в таблице.

Тестирование контроллеров.
Тестированию подлежат только методы контроллера, репозитории и взаимодействие с БД уже считаются оттестированными. Соответственно, протестировать вы должны правильность сериализации/десериализации объектов, а также возвращаемые HTTP Response Codes. 
Варианты реализации:
- Тестирование проводится на той же БД
- Вместо БД реализовать простой in-memory репозиторий, который будет хранить все записи в памяти, в виде List , например. Запускаете веб-сервер с использованием данного репозитория
- Используете Moq для создания репозитория-заглушки

В последних двух случаях необходимо реализовать интерфейс IAsyncLifetime для класса-тестов, в методе инициализации которого запуска приложение нужными параметрами:
```C#
var hostBuilder = Program.CreateHostBuilder(new string[0])
    .ConfigureWebHost(webHostBuilder =>
    {
        webHostBuilder.UseTestServer();
    })
    .ConfigureServices((_, services) =>
    {
        services.AddSingleton(_repositoryMockObject);
    });

var host = await hostBuilder.StartAsync();
_httpClient = host.GetTestClient();
```

2022-04-07 18:02 UTC, SirlLizz commented
Можно повторный ревью?

2022-04-08 13:34 UTC, SirlLizz commented
А что лучше всего все таки брять за основу для клиента? Делать на razer pages? Или можно как-то чистый html и js поднять на шарповском веб сервере?

2022-04-09 08:22 UTC, kolyanch requested changes
1. Тесты по прежнему вызывают вопросы. Отсутствует какое-либо упоминание БД или настроек в этом проекте. NHibernateSession содержит вызов RecoverConfiguration, но проект с тестами не содержит никаких настроек. Все тесты сейчас не проходят на чистой машине. Предполагайте, что на компьютере, где будут запускаться тесты не будет ничего, кроме быть может подключения к серверу БД, при этом самой БД может и не быть. При этом вам как раз пригодится метод GenerateSchema, который сейчас нигде не используется. Его вызов нужно будет обернуть в Fixture
2. Предполагается, что метод POST для Order может ещё создать запись в Product?
![image](https://user-images.githubusercontent.com/73119715/162563223-4be4bee6-394a-40a1-b380-4446058855b8.png)

2022-04-09 08:22 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Connection/NHibernateSession.cs
> +        public static void GenerateSchema()
Данный метод нигде не вызывается

2022-04-09 08:22 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Connection/NHibernateSession.cs
> +            Configuration cfg = NHibernateSession.RecoverConfiguration();
NHibernateSession в данном случае указывать не нужно

2022-04-09 08:22 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Model/Customer.cs
> +        }
Что это?

2022-04-09 08:25 UTC, kolyanch commented
> А что лучше всего все таки брять за основу для клиента? Делать на razer pages? Или можно как-то чистый html и js поднять на шарповском веб сервере?

Можете использовать чистый html/js/css. Для этого из проекта уберите все что связано с Razor-страницами и Startup расчистите.

2022-04-09 08:26 UTC, kolyanch commented
Дополнительно к поледним замечаниям - уберите Conflict() из всех контроллеров

2022-04-09 09:52 UTC, SirlLizz commented
> 2. Предполагается, что метод POST для Order может ещё создать запись в Product?

Нет, почему это? Он принимает на вход лист products, которые уже есть в бд

2022-04-09 12:11 UTC, SirlLizz commented
> Можете использовать чистый html/js/css. Для этого из проекта уберите все что связано с Razor-страницами и Startup расчистите.

А как настроить веб-сервер для старта html страниц?

2022-04-11 04:44 UTC, kolyanch commented
> > 2. Предполагается, что метод POST для Order может ещё создать запись в Product?
> 
> Нет, почему это? Он принимает на вход лист products, которые уже есть в бд

Согласно Swagger описанию у вас сейчас возможен вариант, когда на вход метода POST или PUT для ресурса Order подается список продуктов. При этом не понятно или предполагается, что эти продукты уже есть в БД, или если их указать, то они будут созданы. Если протестировать, то в реальности продукты создаются при создании заказа. 

Кроме этого по текущей структуре БД продукт может относиться только к одному заказу. В таблице Products будет явно фигурировать идентификатор заказа.

Самый лучший путь решения - добавить ещё один класс для реализации связи многие ко многим между заказами и продуктами.   Назвать ProductInOrder или аналогичным образом. В рамках API реализовать дополнительный контроллер для этого класса.

Также никто не запрещает использовать DTO (Data Transformation Objects): заводите дополнительный класс, содержащий только свойства, которые будут использованы при работе методов контроллеров. К примеру, если вы хотите явным образом запретить создание Customer при создании Order, заводите DTO следующего вида:
```C#
public class OrderDto
{
        /// <summary>Field Including Order ID</summary>
        public int OrderId { get; set; }
        /// <summary>Order Customer Id</summary>
        public int CustomerId { get; set; }
        /// <summary>Field Including Order Status</summary>
        public int Status { get; set; }
        /// <summary>Field Including Order Price</summary>
        public double Price { get; set; }
        /// <summary>Field Including Order Date</summary>
        public DateTime Date { get; set; }
}
```

Его используете в контроллере для методов POST и PUT. Отличие от основного класса Order - поле CustomerId является просто идентификатором и нет никаких виртуальных свойств, так как этот класс в БД сохранять не планируется. Order в OrderDto преобразуете руками или с использованием AutoMapper

2022-04-11 04:47 UTC, kolyanch commented
> > Можете использовать чистый html/js/css. Для этого из проекта уберите все что связано с Razor-страницами и Startup расчистите.
> 
> А как настроить веб-сервер для старта html страниц?

Никаких дополнительных настроек не нужно, просто добавляете страницы в wwwroot. Для отладки укажите в настройках проекта с какой страницы стартовать (поле URL):

![image](https://user-images.githubusercontent.com/73119715/162666677-3d244cdf-2a03-48b9-9617-9c865b82e675.png)

2022-04-11 18:33 UTC, SirlLizz commented
> Никаких дополнительных настроек не нужно, просто добавляете страницы в wwwroot. Для отладки укажите в настройках проекта с какой страницы стартовать

Я, видимо, даже с этим справиться не могу..
![k](https://user-images.githubusercontent.com/73231157/162806213-41dbc41f-61e1-458e-8a85-951763ccac7e.gif)
.

2022-04-12 04:36 UTC, kolyanch commented
Сделайте пуш и пока сосредоточтесь на серверной части. Там есть что доделать. На занятии посмотрим в чем может быть проблема

2022-04-15 16:17 UTC, SirlLizz commented
Можно повторный ревью?

2022-04-16 12:12 UTC, kolyanch requested changes
Сделать code cleanup для всего солюшена

2022-04-16 12:12 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Controllers/OrderController.cs
> +        [HttpPost("{id:int}/product")]
Маршрут должен быть одинаковым для всех методов работы с продуктами. В данном случае должен быть {id:int}/products

2022-04-16 12:12 UTC, kolyanch commented on src/AccountingSystem/AccountingSystem/Repository/OrderRepository.cs
> +                        ISession session = NHibernateSession.OpenSession();
Поехала разметка кода

2022-04-16 12:12 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/CustomerControllerTests.cs
> +        public async Task GetCustomerWithID()
*GetCustomerWithID

2022-04-16 12:12 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/OrderControllerTests.cs
> +        protected readonly ITestOutputHelper Output;
Неиспользуемое поле

2022-04-16 12:12 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/OrderControllerTests.cs
> +        public async Task GetOrderWithID()
*GetOrderWithID

2022-04-16 12:12 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/OrderControllerTests.cs
> +        public async Task GetProductWithID()
*GetProductWithId

2022-04-16 12:12 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/OrderControllerTests.cs
> +        public async Task GetAllPrice()
Данный факт не срабатывает на чистой машине

2022-04-16 12:12 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/CustomerRepositoryTests.cs
> +            int count = repository.GetCustomers().Count;
Переменная count нигде не используется

2022-04-16 12:12 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/CustomerRepositoryTests.cs
> +            int count = repository.GetCustomers().Count;
Переменная count нигде не используется

2022-04-16 12:24 UTC, SirlLizz commented on src/AccountingSystem/TestServerAccountingSystem/CustomerControllerTests.cs
> +        public async Task GetCustomerWithID()
А что тут не так?

2022-04-16 12:27 UTC, SirlLizz commented on src/AccountingSystem/TestServerAccountingSystem/OrderControllerTests.cs
> +        public async Task GetAllPrice()
Он не может нормально отработать, потому что на момент запроса в базе разное количество orders, поэтому его нельзя правильно протестировать

2022-04-16 12:27 UTC, SirlLizz commented on src/AccountingSystem/TestServerAccountingSystem/OrderControllerTests.cs
> +        public async Task GetAllPrice()
Просто удалить тест?

2022-04-16 12:29 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/CustomerControllerTests.cs
> +        public async Task GetCustomerWithID()
Смените имя метода на GetCustomerWithId

2022-04-16 12:39 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/OrderControllerTests.cs
> +        public async Task GetAllPrice()
Удалять не нужно. Нужно сделать так, чтобы он работал:
- предзаполнить таблицу Orders
- выполнить расчет
- сравнить с результатом

2022-04-16 13:00 UTC, SirlLizz commented
Все исправил, посмотрите, пожалуйста

2022-04-16 13:08 UTC, kolyanch commented
Не вижу, видимо пуш не сделали

2022-04-16 13:23 UTC, SirlLizz commented
Сделал, теперь есть

2022-04-16 13:41 UTC, kolyanch commented
- Не устранено одно оставшееся замечение
- По прежнему в проекте есть неиспользуемые using
- Для тестов необходимо удалять ранее созданную Sqlite базу, иначе тесты могут не сработать. Добавьте в Fixture File.Delete, если файл БД уже существует
- Классы тестов CustomerRepositoryTests и OrderRepositoryTests сейчас могут не выполниться одновременно. Необходимо использовать Collection Fixture https://xunit.net/docs/shared-context , если вы хотите прогонять все тесты на одной базе данных, а не пересоздавать её для каждого класса тестов

2022-04-16 16:03 UTC, SirlLizz commented
> * Для тестов необходимо удалять ранее созданную Sqlite базу, иначе тесты могут не сработать. Добавьте в Fixture File.Delete, если файл БД уже существует

А может лучше на dispose забиндить?

2022-04-16 16:06 UTC, kolyanch commented
Можете Dispose сделать

2022-04-16 16:12 UTC, SirlLizz commented
Исправил все

2022-04-16 16:38 UTC, SirlLizz commented
Можете посмотреть?

2022-04-16 17:55 UTC, kolyanch commented
После последнего коммита Fixture вообще не используется. Вы забыли реализовать собственно коллекцию. В документации xUnit класс DatabaseCollection найдите

2022-04-16 18:11 UTC, SirlLizz commented
Так? Вроде исправил

2022-04-17 12:51 UTC, kolyanch requested changes

2022-04-17 12:51 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/RepositoryFixture.cs
> +            File.Delete(@"bin\Debug\net5.0\AccountingSystem.db3");
Почему такой странный путь к файлу? Он должен совпадать с путем, указанным в настройках

2022-04-17 12:51 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/CustomerControllerTests.cs
> +    public class CustomerControllerTests
Данный класс тестов опосредованно использует базу данных. Поэтому он тоже должен быть помечен аттрибутом коллекции тестов

2022-04-17 12:51 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/DatabaseCollection.cs
> +    [Collection("Accounting System")]
Это неправильный аттрибут

2022-04-17 12:51 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/OrderControllerTests.cs
> +    public class OrderControllerTests
Данный класс тестов опосредованно использует базу данных. Поэтому он тоже должен быть помечен аттрибутом коллекции тестов

2022-04-17 13:02 UTC, SirlLizz commented
Исправил

2022-04-17 13:28 UTC, kolyanch commented
После последнего коммита идентификаторы в таблицах БД стали автоинкрементными. Тесты перестали работать

2022-04-17 14:16 UTC, SirlLizz commented
Исправил

2022-04-17 14:27 UTC, kolyanch commented
Не вижу пуша

2022-04-17 15:33 UTC, SirlLizz commented
Запушил

2022-04-17 15:40 UTC, kolyanch requested changes

2022-04-17 15:40 UTC, kolyanch commented on src/AccountingSystem/TestServerAccountingSystem/DatabaseCollection.cs
> +    internal class DatabaseCollection : ICollectionFixture<RepositoryFixture>
Данный класс должен быть публичным

2022-04-17 15:43 UTC, SirlLizz commented
Исправил, посмотрите, пожалуйста

2022-04-17 15:46 UTC, kolyanch approved these changes

2022-04-17 15:46 UTC, closed without merging

2022-04-17 15:48 UTC, SirlLizz commented
PR на клиент после защиты открывать можно только?

2022-04-17 15:49 UTC, kolyanch commented
После защиты и после того как он будет готов