ClientAccountingSystem
itsec-labs/dotnet-2 pull request #3
Opened 2022-04-21 18:06 UTC by SirlLizz

Студент Моисеев, группа 6312, клиент на html+js

2022-04-22 06:36 UTC, kolyanch requested changes
Общее замечание: в js-коде не должно быть захардоженого урла к серверу. Каким образом этот проект можно задеплоить хоть куда-нибудь? После деплоя менять все js-файлы?

Замечания по UI:
- статус сейчас это просто какое-то число. Для пользователя непонятно как этим пользоваться. Заведите перечисление возможных статусов и отображайте их названия
- приложение позволяет вводить отрицательную стоимость. Это неверно
- в заказе и в продукте присутствует стоимость. Сейчас они никак не связаны между собой. При изменении привязанных к заказу продуктов необходимо автоматически изменять стоимость заказа в целом на суммарную по продуктам
- для упрощения вводу дату автозаполнять текущей с возможностью последующего изменения пользователем
- для изменения заказа сейчас пользователю необходимо выбирать его идентификатор. Это не удобно. Отображать покупателя и дату заказа вместо идентификатора

2022-04-22 06:36 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/js/add-customer/add-customer.js
> +        let xhttp = new XMLHttpRequest();
Использовать const вместо let

2022-04-22 06:36 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/js/add-customer/add-customer.js
> +        xhttp.open("POST", "https://localhost:5002/api/Customer/");
Привести кавычки во всех файлах к единому стилю

2022-04-22 06:36 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/js/add-customer/add-customer.js
> +            if (xhttp.status == 200) {
Использовать === при всех сравнениях во всем js-коде

2022-04-22 06:36 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/js/add-customer/add-customer.js
> +    return flag
Не хватает точек с запятой. Используйте let и const.
Аналогично в других js-файлах

2022-04-22 06:36 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/pages/add-customer.html
> +                        <input type="text" id='name' maxlength=38 class='field'/>
type - двойные кавычки
id - уже одинарные
maxlength - вообще без них

Привести к единому стилю и так во всех html-файлах

2022-04-22 08:38 UTC, SirlLizz commented
> Общее замечание: в js-коде не должно быть захардоженого урла к серверу. Каким образом этот проект можно задеплоить хоть куда-нибудь? После деплоя менять все js-файлы?

А где это можно указать?

2022-04-22 12:48 UTC, kolyanch commented
В данном случае у вас 2 варианта:
1. Заводить отдельный статический json или просто глобальную переменную. Используете её при отправке запросов.
2. Делаете в клиентском проекте отдельный контроллер, который возвращает этот самый URL из настроек. При загрузке странице первым делом отправляете запрос на локальный адрес получения адреса сервера.

2022-04-22 21:08 UTC, SirlLizz commented
Посмотрите, пожалуйста, вроде все

2022-04-24 15:55 UTC, kolyanch requested changes
Папку с клиентским проектом переименовать в ClientAccountingSystem. Аналогичным образом сменить namespace во всех cs-файлах проекта

2022-04-24 15:55 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/common/constants.js
> +﻿const url = 'https://localhost:5002/'
Добавить точку с запятой в конце

2022-04-24 15:55 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/js/add-product/add-product.js
> +            if (xhttp.status == 200) {
===

2022-04-24 15:55 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/js/start-customer/start-customer.js
> +        const id = document.getElementById('updateCustomerChoose').value
Не хватает точки с запятой

2022-04-24 15:55 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/js/start-order/start-order.js
> +            rows += '<td><table>'
Не хватает точки с запятой

2022-04-24 15:55 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/js/start-order/start-order.js
> +                    const id = document.getElementById('updateOrderChoose').value
Не хватает точки с запятой

2022-04-24 15:55 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/js/start-order/start-order.js
> +        const id = document.getElementById('updateOrderStatusChoose').value
Не хватает точки с запятой

2022-04-24 15:55 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/js/start-order/start-order.js
> +            if (xhttp.status == 200) {
===

2022-04-24 15:55 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/js/start-order/start-order.js
> +            if (xhttp.status == 200) {
===

2022-04-24 15:55 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/js/start-order/start-order.js
> +            if (xhttp.status == 200) {
===

2022-04-24 15:55 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/js/start-order/start-order.js
> +            if (xhttp.status == 200) {
===

2022-04-24 15:55 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/js/start-order/start-order.js
> +        alert('All Price Orders is ' + xhttp.responseText)
Не хватает точки с запятой

2022-04-24 15:55 UTC, kolyanch commented on src/AccountingSystem/WebApplication2/wwwroot/js/start-order/start-order.js
> +        alert('All Count Products By Order Monthly is ' + xhttp.responseText)
Не хватает точки с запятой

2022-04-24 17:58 UTC, SirlLizz commented
Исправил, можете посмотреть?

2022-04-25 08:19 UTC, kolyanch approved these changes

2022-04-25 08:19 UTC, closed without merging