Сапёр онлайн, клиент
itsec-labs/dotnet-2 pull request #31
Opened 2022-06-02 07:35 UTC by Divanchik

Шепляков Дмитрий 6312

2022-06-02 13:20 UTC, kolyanch commented
Для обновления списка пользователей переведите _players на MVVM:
1. В MainViewModel добавьте:
```C#
public ObservableCollection<PlayerInfo> Players { get; set; } = new();
```
2. В MainWindow.axaml.cs функция PlayersUpdate будет иметь вид:
```C#
private async void PlayersUpdate()
{
    while (true)
    {
        Thread.Sleep(2000);
        if (_wire is not { IsConnected: true }) return;

        await _wire.UpdatePlayers();
        Dispatcher.UIThread.Post(() =>
        {
            if (DataContext is not MainWindowViewModel viewModel) return;
            viewModel.Players.Clear();
            foreach (var info in _wire.Players)
            {
                Console.WriteLine($"got {info.Name}'s stats, {info.PlayCount}/{info.WinCount}/{info.WinStreak}");
                viewModel.Players.Add(info);
            }
        }, DispatcherPriority.Background);
    }
}
```
3. В конструкторе MainWindow убрать присвоение _playerList.Items и вообще удалить поля _players и _playerList.
4. В MainWindow.axaml добавить Binding:
```XAML
<ItemsControl Grid.Row="1" Grid.Column="0" Background="White" Margin="4" Items="{Binding Players}">
	<ItemsControl.ItemTemplate>
		<DataTemplate>
			<Label Content="{Binding Stats}" Margin="1" />
		</DataTemplate>
	</ItemsControl.ItemTemplate>
</ItemsControl>
```

Этого должно хватить для вывода списка игроков.

2022-06-07 06:43 UTC, Divanchik commented
@kolyanch запрашиваю ревью кода

2022-06-07 07:12 UTC, kolyanch requested changes
- Сделать code cleanup
- В readme.md добавить скриншоты приложения

2022-06-07 07:12 UTC, kolyanch commented on MinesweeperClient/Views/MainWindow.axaml.cs
> +        Label _flagsLabel;
private readonly

2022-06-07 07:12 UTC, kolyanch commented on MinesweeperClient/Views/MainWindow.axaml.cs
> +        int _flagsCounter;
private

2022-06-07 07:12 UTC, kolyanch commented on MinesweeperClient/Views/MainWindow.axaml.cs
> +        public Connection? _wire;
Переименовать в Wire

2022-06-07 07:12 UTC, kolyanch commented on MinesweeperClient/Views/MainWindow.axaml.cs
> +            GameMessage msg = new();
Ненужная инициализация, переместить объявление внутрь while и совместить с присвоением _wire.Peek()

2022-06-07 07:12 UTC, kolyanch commented on MinesweeperClient/Views/MainWindow.axaml.cs
> +        void FlagsUpdate()
private

2022-06-07 07:12 UTC, kolyanch commented on MinesweeperClient/Views/MainWindow.axaml.cs
> +            int flags_cache = _flagsCounter;
Нарушение правил именования переменных

2022-06-07 18:45 UTC, kolyanch commented
Cleanup не сделан

2022-06-07 18:54 UTC, Divanchik commented
@kolyanch а теперь?

2022-06-07 18:57 UTC, kolyanch requested changes

2022-06-07 18:57 UTC, kolyanch commented on MinesweeperClient/Program.cs
> +using Avalonia.Controls.ApplicationLifetimes;
Это точно нужно?

2022-06-07 18:57 UTC, kolyanch commented on MinesweeperClient/ViewModels/ViewModelBase.cs
> +using ReactiveUI;
Все эти namespace-ы точно нужны?

2022-06-07 19:05 UTC, kolyanch approved these changes

2022-06-07 19:05 UTC, closed without merging