Казанцев Павел 6311 (Чат, SignalR)
itsec-labs/dotnet-2 pull request #34
Opened 2022-06-05 23:23 UTC by Dryg1214

Репозиторий с коммитами
https://github.com/Dryg1214/ChatServer

2022-06-06 06:23 UTC, navna requested changes
Глобально:
1. На сервере включить `nullable` и исправить предупреждения, если появятся.
2. Смотреть внутренности клиента времени нет, но по внешнему виду нужно исправить:
    - **LoginWindow**. Если его развернуть на весь экран, то все внутренности окна (поле ввода, его подчеркивание, кнопка) разъедутся наистрашнейшим образом.
    - **LoginWindow**. Сворачивание из полноэкранного режима обратно в оконный не работает (по крайней мере, на моей Windows 10).
    - **LoginWindow**. Перечисленные выше замечания исправить: либо сделать адекватный масштабируемый макет для окна и работующую кнопку перехода из полноэкранного режима в оконный; либо вообще убрать эту кнопку и/или все кнопки из заголовка окна.
    - **LoginWindow**. Окно не является перемещаемым, что плохо.
    - **MainWindow**. Аналогично не работает кнопка сворачивания из полноэкранного режима обратно в оконный.
    - **MainWindow**. Задать некоторые минимальные размеры окна, чтобы его нельзя было сделать меньше некоторых размеров.

2022-06-06 06:23 UTC, navna commented on ChatServer/Startup.cs
> +            services.AddSingleton<ChatHub>();
По умолчанию, хабы [являются](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-5.0) transient-сервисами и регистрируются фреймворком при вызове `endpoints.MapHub<...>(...)`. Тем не менее, вы его явно регистрируете как singleton, чтобы обеспечить сохранение состояния. Но это может привести к абсолютно непредсказуемым последствиям (например, при использовании `Hub.Context`, который не может быть всё время одним и тем же объектом и т. п.). Несмотря на кажущуюся работоспособность вашего проекта он таковым не является.

1. `ChatHub` должен быть transient-сервисом. Вы его не можете регистрировать как singleton. Следующую строчку удалить.
```
services.AddSingleton<ChatHub>();
```

2. После выполнения п. 1 вы не можете заводить в `ChatHub` какие-либо поля для сохранения состояния, т. к. под каждый запрос будет создаваться отдельный объект хаба. В этом случае все поля и методы вынести в отдельный класс, например, `ChatService`. Именно его зарегистрировать как singleton:
```
services.AddSingleton<ChatService>();
```

3. В transient-хаб `ChatHub` без состояния заинъектить singleton-сервис `ChatService` и свести все методы хаба к вызову методов сервиса.

2022-06-06 06:23 UTC, navna commented on ChatServer/Startup.cs
> +            services.AddControllers();
Эту строчку удалить, контроллеры в данном сервере не используются.

2022-06-06 06:23 UTC, navna commented on ChatServer/Startup.cs
> +            app.UseAuthorization();
Эту строчку удалить, фреймвочные средства авторизации в данном сервере не используется.

2022-06-06 06:23 UTC, navna commented on ChatServer/Startup.cs
> +                endpoints.MapControllers();
Эту строчку удалить, контроллеры в данном сервере не используются.

2022-06-06 10:13 UTC, Dryg1214 reviewed
Исправлен код

2022-06-06 10:38 UTC, navna requested changes
1. Не исправлен первый пункт прошлого [ревью](https://github.com/itsec-labs/dotnet-2/pull/34#pullrequestreview-996172494)
2. Черный цвет логина собеседника в окне чата на сером фоне читабельным не является. Исправьте.

2022-06-07 05:56 UTC, navna approved these changes

2022-06-07 05:57 UTC, navna commented
От очной защиты освобождаю.

2022-06-07 05:57 UTC, closed without merging