Серверная часть Шафранюк Роман группа 6312
itsec-labs/dotnet-2 pull request #4
Opened 2022-04-27 13:24 UTC by RomanShafranyuk

2022-04-27 13:43 UTC, kolyanch requested changes

2022-04-27 13:43 UTC, kolyanch commented on ChatServer/Repositories/RoomRepository.cs
> +        public ConcurrentDictionary<string, RoomNetwork> Rooms { get { return _current; } set { _current = value; } }
Использовать expression body

2022-04-27 13:43 UTC, kolyanch commented on ChatServer/Repositories/RoomRepository.cs
> +                using FileStream streamMessage = File.Create(Key + ".json");
Использовать await using

2022-04-27 13:43 UTC, kolyanch commented on ChatServer/Repositories/RoomRepository.cs
> +            foreach (var (Key, Value) in _current)
* (key, value)

2022-04-27 13:43 UTC, kolyanch commented on ChatServer/RoomNetwork.cs
> +        public bool FindUser(string userName) => Users.Where(x => x.Name == userName).Count() == 0;
Использовать Any или 
```C#
Users.Count(x => x.Name == userName) == 0
```

2022-04-27 13:43 UTC, kolyanch commented on ChatServerTests/Repositories/RoomRepositoryTests.cs
> +namespace ChatServer.Repositories.Tests
namespace должен быть ChatServerTests.Repositories

2022-04-27 13:43 UTC, kolyanch commented on ChatServerTests/Repositories/UserRepositoryTests.cs
> +namespace ChatServer.Repositories.Tests
namespace должен быть ChatServerTests.Repositories

2022-04-27 13:43 UTC, kolyanch commented on ChatServerTests/RoomNetworkTests.cs
> +namespace ChatServer.Tests
namespace должен быть ChatServerTests

2022-04-27 16:25 UTC, kolyanch commented
Ещё замечание: если используется файловое хранилище, то на уровне репозиториев необходимо обеспечить одновременной записи в файлы. Сейчас может возникнуть ситуация, когда при одновременных запросах от нескольких пользователей, произойдет исключение при записи в файл.

2022-04-27 17:36 UTC, RomanShafranyuk commented
Не совсем понял, что требуется

2022-04-28 04:46 UTC, kolyanch commented
У вас в ChatService как в методе Create, так и в методе Join происходит вызов метода WriteAsync для репозиториев. Предположим в чат подключаются одновременно 100 пользователей. Происходит вызов метода Join и запускается 100 одновременных записей в файл. При этом возникнет ошибка доступа к файлу, в него может писать только один поток. 

Поэтому необходимо исправить вызовы метода записи так, чтобы не происходило одновременного доступа к файлам из разных потоков. Либо используйте lock для блокировки ресурса, либо избавтесь от вызова записи в файл в классе ChatService и выполняйте параллельную записи на диск файлов репозиториев с использованием IHostedService.

2022-04-28 17:29 UTC, RomanShafranyuk commented
Т.е. все таки lock нельзя использовать? Или чего-то не хватает?

2022-04-28 17:47 UTC, kolyanch commented
Lock можно использовать. Но кое-чего не хватает. Учтите, что экземпляр класс ChatService создается при каждом запросе. Это определяет время жизни объекта, который вы используете для lock

2022-04-28 18:11 UTC, RomanShafranyuk commented
Т.е. lock должен быть каким то общим ресурсом? Если так, то не совсем понятно, как оно должно выглядеть

2022-04-29 06:04 UTC, RomanShafranyuk commented
Со static тест также не проходит :(

2022-04-29 06:44 UTC, kolyanch commented
Учитывайте, что в lock нужно обернуть все операции с файлами. К примеру у вас в том же методе идет вызов ReadAsyncToFile без лока (эту функцию кстати нужно переименовать в ReadFromFileAsync).

2022-04-29 13:57 UTC, RomanShafranyuk commented
После того как считывание файла взял в _lock возникает ошибка с ключами: Функция полностью отрабатывает, а затем возникает исключение о том, что ключи в словаре не найдены

2022-04-30 15:04 UTC, kolyanch commented
Сделайте пуш в ваш репозиторий

2022-05-02 08:56 UTC, RomanShafranyuk commented
Изменения загрузил

2022-05-02 13:09 UTC, kolyanch commented
У вас сейчас внутри lock вызываются асинхронные методы, результата выполнения которых вы не дожидаетесь. Поэтому и словари пусты, они еще не прогрузились к моменту, когда к ним производится обращение.
Поэтому добавьте ожидание выполнения или используйте другой механизм вместо lock:
https://blog.cdemi.io/async-waiting-inside-c-sharp-locks/

2022-05-02 14:14 UTC, RomanShafranyuk commented
Изменения проведены, тест проходит.

2022-05-02 15:36 UTC, kolyanch requested changes

2022-05-02 15:36 UTC, kolyanch commented on ChatServer/Services/ChatService.cs
> +        private static object _lock = new object();
Этот объект сейчас никак не используется

2022-05-02 15:36 UTC, kolyanch commented on ChatServer/Services/ChatService.cs
> +        private static SemaphoreSlim semaphoreSlim = new SemaphoreSlim(1, 1);
Переименовать в SemaphoreSlim
Пометить как readonly

2022-05-02 15:36 UTC, kolyanch commented on ChatServer/Services/ChatService.cs
> +            var tcs = new TaskCompletionSource<int>();
Данная переменная нигде не используется

2022-05-02 15:36 UTC, kolyanch commented on ChatServer/Services/ChatService.cs
> +                    return;
return в данном случае не нужен

2022-05-02 15:36 UTC, kolyanch commented on ChatServer/Services/ChatService.cs
> +                return;
return в данном случае не нужен

2022-05-02 15:36 UTC, kolyanch commented on ChatServer/Services/ChatService.cs
> +                        var CurrentMessage = requestStream.Current;
Переименовать в currentMessage

2022-05-02 15:53 UTC, RomanShafranyuk commented on ChatServer/Services/ChatService.cs
> +                        var CurrentMessage = requestStream.Current;
После исправлений возникла проблема с Git Hub Actions: System.IO.IOException : The process cannot access the file '/home/runner/work/dotnet-2/dotnet-2/ChatServerTests/bin/Debug/net5.0/users.json' because it is being used by another process

2022-05-02 15:53 UTC, RomanShafranyuk commented
После исправлений возникла проблема с Git Hub Actions: System.IO.IOException : The process cannot access the file '/home/runner/work/dotnet-2/dotnet-2/ChatServerTests/bin/Debug/net5.0/users.json' because it is being used by another process

2022-05-02 17:01 UTC, RomanShafranyuk commented
Источником ошибок послужил readonly у семафора

2022-05-02 17:23 UTC, kolyanch requested changes

2022-05-02 17:23 UTC, kolyanch commented on ChatServer/Services/ChatService.cs
> +                        Console.WriteLine(requestStream.Current);
Вывод в консоль использовать нельзя. Используйте ILogger для этих целей

2022-05-02 17:23 UTC, kolyanch commented on ChatServerTests/Services/ChatServiceTests.cs
> +namespace ChatServer.Services.Tests
Неправильный namespace

2022-05-02 17:23 UTC, kolyanch commented on ChatServerTests/Services/ChatServiceTests.cs
> +    };
Разметка поехала

2022-05-02 18:02 UTC, RomanShafranyuk commented
После замены произошли очередные проблемы в Actions

2022-05-03 06:20 UTC, kolyanch commented
Сейчас один и тот же семафор используется для нескольких файлов. Попробуйте перенести логику блокировки ресурсов в репозитории, в соответствующие методы чтения/записи. Семафоров будет как минимум 2, для каждого класса.

2022-05-03 08:06 UTC, RomanShafranyuk commented
Исправлено, тест проходит

2022-05-03 08:18 UTC, kolyanch approved these changes

2022-05-03 08:18 UTC, closed without merging