Дышловой 6312 Клиент (TelegramBot, OpenApi, Xml)
itsec-labs/dotnet-2 pull request #42
Opened 2022-06-07 01:57 UTC by Gentlestack

Пока клиент не срабатывает даже на добавление, вся логика добавления реализована, но клиент не собирается, при вызове контроллера выдает "error CS0246: The type or namespace name 'TelegramBotServer' could not be found"
Также при разработке возникли следующие вопросы:
1) Как передать user и userId полученные в LoginViewModel в другие ViewModels (например userId в AddReminderViewModel)
2) Как закрыть окно в котором была нажата кнопка (например LoginWindow, при нажатии кнопки "Ok")
3) Как обратиться к уже созданному ранее окну, в ViewModel, нужно ли передавать экземпляр данного окна в конструкторе
Извините за грязный pull request, заранее спасибо

2022-06-07 04:50 UTC, kolyanch commented
Ошибка компиляции. Что делать по шагам:
1. Правой кнопкой по проекту с клиентом, Add -> Connected Service
2. В блоке Service References будет swagger.json, который добавили вчера.
3. Нажать на многоточие
![image](https://user-images.githubusercontent.com/73119715/172298126-1160d70c-5762-49cb-960e-119052ca60fe.png)
4. Выбрать View generated code
5. Откроется файл со сгенерированным кодом клиента
6. Скопировать весь код
7. Создать новый файл, назвать, например, TelegramBotServer. Вставить в него весь скопированный на шаге 6 код
8. Снова повторить шаги 1-3, но выбрать Remove

После этого проект должен компилироваться и запускаться

2022-06-07 05:29 UTC, kolyanch commented
> 1. Как передать user и userId полученные в LoginViewModel в другие ViewModels (например userId в AddReminderViewModel)

Текущий код конструктора LoginViewModel выглядит следующим образом:
```C#
public LoginViewModel()
{
	MainWindow mainWindow = new MainWindow(this);
	OkCommand = new Command(async _ =>
	{
		using var httpClient = new HttpClient();
		var telegramBotServer = new TelegramBotServer("/api/User/{userid}", httpClient);  // адрес взят из swagger.json, клиент не собирается с этой строкой кода
		await telegramBotServer.UserAsync(UserId);
		mainWindow.Show();
		// todo закрытие LoginWindow из которого вызван OkCommand, на данный момент не знаю как это сделать
	}, _=> true);
}
```

Какие в нем ошибки:
1. MainWindow нужно создавать только в случае, если пользователь нажмет на кнопку OK, т.е. внутри команды
2. В конструктор TelegramBotServer передан неправильный аргумент. Вместо "/api/User/{userid}" должен быть базовый адрес вашего сервера. Его необходимо взять из настроек, тем более он у вас там уже есть.
3. Результат получения информации о пользователе никуда не сохраняется и никак не анализируется

Код каким он должен примерно быть:
```C#
public LoginViewModel()
{
	OkCommand = new Command(async _ =>
	{
		using var httpClient = new HttpClient();
		var telegramBotServer = new TelegramBotServer(Properties.Settings1.Default.OpenApiServer, httpClient);
		var user = await telegramBotServer.UserAsync(UserId);
		if (user != null)
		{
			var mainWindow = new MainWindow(new MainViewModel { User = user });
			mainWindow.Show();
		}
		else
		{
			MessageBox.Show("Указанный пользователь не найден", "Ошибка", MessageBoxButton.OK,
				MessageBoxImage.Error);
		}
	}, _=> true);
}
```

Обратите внимание:
1. Основное окно приложения отображается только в ситуации, если пользователь найден на сервере. 
2. Конструктор MainWindow должен принимать MainViewModel, а не LoginViewModel

2022-06-07 05:36 UTC, kolyanch commented
> 2. Как закрыть окно в котором была нажата кнопка (например LoginWindow, при нажатии кнопки "Ok")

Если вы не используете ReativeUI, то только нарушением MVVM, когда ViewModel узнает о View.
Для этого необходимо передать в команду OkCommand в качестве параметра само окно.

На уровне xaml это будет выглядеть следующим образом (обратите внимание на то, что добавлен DataContext):
```XML
<Window
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:viewModels="clr-namespace:BotClient.ViewModels" x:Class="BotClient.Views.LoginWindow"
        mc:Ignorable="d"
        Title="LoginWindow" Height="230" Width="800">

    <Window.DataContext>
        <viewModels:LoginViewModel/>
    </Window.DataContext>

    <Grid Height="243" VerticalAlignment="Top">
        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition Height="0*"/>
            <RowDefinition Height="0*"/>
        </Grid.RowDefinitions>
        <StackPanel VerticalAlignment="Top" Margin="0,28,0,0" Height="148">
            <Label Content="Enter your login:" HorizontalAlignment="Left" Height="33" Width="102"/>
            <TextBox Height="76" Width="620" Text="{Binding UserId}"/>
            <Button Command="{Binding OkCommand}" 
                    CommandParameter="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Window}}}"
                    Content="OK"/>
        </StackPanel>
    </Grid>
</Window>
```

На уровне самой команды:
```C#
OkCommand = new Command(async commandParameter =>
{
	if (commandParameter is not Window window) return;

	using var httpClient = new HttpClient();
	var telegramBotServer = new TelegramBotServer(Properties.Settings1.Default.OpenApiServer, httpClient);  
	var user = await telegramBotServer.UserAsync(UserId);
	if (user != null)
	{
		var mainWindow = new MainWindow(new MainViewModel { User = user });
		mainWindow.Show();
		window.Close();
	}
	else
	{
		MessageBox.Show("Указанный пользователь не найден", "Ошибка", MessageBoxButton.OK,
			MessageBoxImage.Error);
	}
}, _ => true);
```

2022-06-07 05:37 UTC, kolyanch commented
> 3. Как обратиться к уже созданному ранее окну, в ViewModel, нужно ли передавать экземпляр данного окна в конструкторе

Не обращайтесь к созданным окнам, у вас их максимум 3 будет. Поэтому проще пересоздавайте каждый раз, передавая новый ViewModel

2022-06-07 16:25 UTC, kolyanch commented
PR уже можно смотреть или ещё будете доделывать?

2022-06-07 16:35 UTC, Gentlestack commented
добавление уже окончательно готово, собираюсь ещё сделать отображение существующих заметок в MainWindow, удаление и изменение заметок через id

2022-06-08 03:58 UTC, kolyanch requested changes
- Правила валидации на данный момент не используются, поэтому лучше их удалить
- Удалить из репозитория файл atm.geojson

2022-06-08 03:58 UTC, kolyanch commented on BotClient/BotClient.csproj
> +  </ItemGroup>
Убрать это

2022-06-08 03:58 UTC, kolyanch commented on BotClient/ViewModels/AddReminderViewModel.cs
> +        private User _user;
Поле нигде не используется, удалите его

2022-06-08 06:19 UTC, kolyanch approved these changes

2022-06-08 06:19 UTC, closed without merging