ATMs map app server w/ unit tests
itsec-labs/dotnet-2 pull request #5
Opened 2022-05-04 18:02 UTC by VladaHaustova

6 вариант, серверная часть
Использовала Microsoft.AspNetCore.Mvc.Testing 5.0.16 версии, потому что .NET 5.0 не поддерживается самой новой версией
Влада Хаустова, 6312-100503D

2022-05-05 04:30 UTC, kolyanch requested changes
- Сделать полный code cleanup для солюшена
- Методы контроллеров и схемы данных должны быть задокументированы, сейчас полностью отсутствует описание:
![image](https://user-images.githubusercontent.com/73119715/166863074-6b7ec03e-74a0-4ca7-b403-2c18f9c53285.png)
- Перечень банкоматов должен быть взят из файла https://github.com/itsec-labs/dotnet-2/blob/main/atm.geojson . В нем же и остаться, баланс денежных средств при этом у вас должен сохраняться в отдельный файл в формате XML по варианту
- Не отработан случай многопоточного вызова методов контроллеров, когда несколько клиентов попытаются одновременно изменить данные, например, баланс. В этой ситуации при текущем варианте произойдет исключение доступа к файлу

2022-05-05 04:30 UTC, kolyanch commented on GeoApp.Tests/ATMRepositoryTests.cs
> +            var ATM = new ATM
Нарушение правил именования.
Переименовать переменную в atm.
И так во всех тестах

2022-05-05 04:30 UTC, kolyanch commented on GeoApp/Controllers/ATMController.cs
> +        private readonly IATMRepository _ATMRepository;
Нарушение правил именования, переименовать в _atmRepository. И так везде

2022-05-05 04:30 UTC, kolyanch commented on GeoApp/Model/ATM.cs
> +        public double y { get; set; }
Нарушение правил именования публичных свойств

2022-05-05 04:30 UTC, kolyanch commented on GeoApp/Model/ATM.cs
> +        public Coords() { }
Зачем нужен этот конструктор?

2022-05-05 04:30 UTC, kolyanch commented on GeoApp/Repository/ATMRepository.cs
> +            }
Использовать LINQ

2022-05-05 04:30 UTC, kolyanch commented on GeoApp/Repository/ATMRepository.cs
> +            }
Использовать LINQ

2022-05-05 04:30 UTC, kolyanch commented on GeoApp/Repository/ATMRepository.cs
> +            var DeletedATM = _ATMs.Find(ATM => ATM.Id == id);
Нарушение правил именования переменных

2022-05-05 04:30 UTC, kolyanch commented on GeoApp/Repository/ATMRepository.cs
> +            var tmp = GetATMById(id);
Переименовать переменную tmp

2022-05-09 18:23 UTC, kolyanch requested changes

2022-05-09 18:23 UTC, kolyanch commented on GeoApp/Controllers/ATMController.cs
> +        public ATMController(IATMRepository ATMrepository)
Нарушение правил именования аргумента. Должно быть atmRepository

2022-05-09 18:23 UTC, kolyanch commented on GeoApp/Model/JsonATMList.cs
> +        public override bool Equals(object o)
Если вы переопределяете Equals, то переопределите GetHashCode

2022-05-09 18:23 UTC, kolyanch commented on GeoApp/Model/JsonATMList.cs
> +            return o is JsonATM aTM &&
Очень странно названная переменная

2022-05-09 18:23 UTC, kolyanch commented on GeoApp/Repository/ATMRepository.cs
> +        private List<JsonATM> _JsonATMs;
Нарушение правил именования приватных полей

2022-05-09 18:23 UTC, kolyanch commented on GeoApp/Repository/ATMRepository.cs
> +            return null;
Убрать это. Какой смысл сравнить с null, а потом возвращать null?

2022-05-09 18:23 UTC, kolyanch commented on GeoApp/Repository/IATMRepository.cs
> +
Зачем данная пустая строка?

2022-05-09 22:03 UTC, VladaHaustova commented
Всё исправила

2022-05-10 02:35 UTC, kolyanch requested changes
1. Добавьте следующий тест:
```
[Fact]
public void ChangeBalance()
{
	ATMRepository repository = new();
	var atms = repository.GetAllATMs();

	var tasks = atms.Select(atm => Task.Run(() =>
	{
		repository.ChangeBalanceById(atm.Properties.Id, 100);
	})).ToArray();
	Task.WaitAll(tasks);
}
```
И добейтесь, что он проходил без исключений
2. В тестовом проекте отсутствует файл atm.geojson, из-за чего ни один тест не проходит

Добейтесь работоспособности всех написанных тестов

2022-05-10 02:35 UTC, kolyanch commented on GeoApp/Repository/IATMRepository.cs
> +
Вы не ту пустую строку удалили)

2022-05-10 02:35 UTC, kolyanch commented on GeoApp/Repository/ATMRepository.cs
> +            return atm ?? null;
Эта строчка по-прежнему вызывает вопросы

2022-05-10 07:02 UTC, VladaHaustova commented
![image](https://user-images.githubusercontent.com/92472083/167567600-a2a3d957-9ee3-467b-a11d-10426a613026.png)

Добавила Ваш тест и исправила Lock для PUT метода, теперь Ваш тест проходит
Файл .geojson загрузила в папку с тестами, но у меня тесты его видят, если он лежит в bin/Debug, а не в корневой папке проекта (как в случае с самим сервером). Поэтому изначально и не загрузила его, а так все написанные тесты проходят, если его положить в папку со скрина

2022-05-10 07:55 UTC, kolyanch commented
Так как файл нужен для тестов необходимо включить его в проект и пометить в свойствах Copy to Output Directory

2022-05-11 06:24 UTC, VladaHaustova commented
Пометила, закоммитила новый .csproj

2022-05-11 06:47 UTC, kolyanch requested changes
Сделать code cleanup

2022-05-11 06:47 UTC, kolyanch commented on GeoApp/Repository/ATMRepository.cs
> +        object locker = new();
Нарушение правил именования приватных полей. Явно указать модификатор доступа

2022-05-11 06:47 UTC, kolyanch commented on GeoApp/Model/JsonATMList.cs
> +                return Int32.Parse(Properties.Id);
Использовать int

2022-05-11 07:01 UTC, kolyanch requested changes
Проверьте файл ATMRepositoryTests.cs на наличие лишних using

2022-05-11 07:01 UTC, kolyanch commented on GeoApp/Repository/ATMRepository.cs
> +        private object _locker = new();
Добавить readonly

2022-05-11 07:03 UTC, VladaHaustova commented
Извините, неиспользуемые usings не сразу серым выделяются, когда файл открываю. Не заметила

2022-05-11 07:15 UTC, kolyanch commented
Для очистки есть волшебная кнопка:

![image](https://user-images.githubusercontent.com/73119715/167790987-ee22eddf-067c-45e9-8ac8-5bf827cc9437.png)

2022-05-11 07:15 UTC, kolyanch approved these changes

2022-05-11 07:15 UTC, closed without merging