Беседина 6312 Список задач
itsec-labs/dotnet-2 pull request #6
Opened 2022-05-06 08:28 UTC by lbesedka

All done

2022-05-06 10:00 UTC, kolyanch requested changes

2022-05-06 12:47 UTC, lbesedka commented on Lab2/Lab2/Repositories/ExecutorRepository.cs
> +            var maxId = _executors.Max(ex => ex.ExecutorId);
Здравствуйте! Я не очень понимаю как сделать, пробовала делать проверки на пустой лист, пробовала добавлять при пустом листе нулевой элемент, пробовала модифицировать конструктор, чтобы пустого листа никогда не существовало.

2022-05-06 13:26 UTC, kolyanch commented on Lab2/Lab2/Repositories/ExecutorRepository.cs
> +            var maxId = _executors.Max(ex => ex.ExecutorId);
Попробуйте:
```csharp
// для исполнителя не задан идентификатор, присваиваем его
if (executor.ExecutorId == default)
{
    if (_executors.Count == 0)
        executor.ExecutorId = 1;
    else
        executor.ExecutorId = _executors.Max(ex => ex.ExecutorId) + 1;
}
```

Но у вас ещё проблемы с методом удаления. Там нужно найти по идентификатору, а только потом удалять

2022-05-07 07:31 UTC, kolyanch requested changes

2022-05-07 07:31 UTC, kolyanch commented on Lab2/Lab2/Repositories/ExecutorRepository.cs
> +                executor.ExecutorId = maxId + 1;
Наличие данного кода приводит к тому, что ни один тест не проходит. Зачем он нужен?

2022-05-07 07:31 UTC, kolyanch commented on Lab2/Lab2/Repositories/TagRepository.cs
> +        public int AddTag(Tags tags)
tags -> tag

2022-05-07 07:31 UTC, kolyanch commented on Lab2/Lab2/Repositories/TaskRepository.cs
> +        public int AddTask(Task tasks)
tasks -> task

2022-05-07 10:47 UTC, kolyanch requested changes
По прежнему не проходят тесты. Напишите дополнительный тест, в котором добавляйте в репозиторий запись без идентификатора. 
Случаи:
- если задан идентификатор объекта - проверить, есть ли такой в коллекции, если есть, то исключение. Если нет - просто добавить его в коллекцию
- если не задан идентификатор
  - при этом коллекция не пуста - сгенерировать идентификатор, присвоить его и добавить объект в коллекцию
  - при этом коллекция пуста - установить идентификатор равным 1, добавить объект в коллекцию

2022-05-07 10:47 UTC, kolyanch commented on Lab2/Lab2/Repositories/ExecutorRepository.cs
> +            var DeletedExecutor = Get(id);
*deletedExecutor

2022-05-07 10:47 UTC, kolyanch commented on Lab2/Lab2/Repositories/TagRepository.cs
> +            var DeletedTag = Get(id);
*deletedTag

2022-05-07 10:47 UTC, kolyanch commented on Lab2/Lab2/Repositories/TaskRepository.cs
> +            var DeletedTask = Get(id);
*deletedTask

2022-05-08 05:30 UTC, kolyanch requested changes

2022-05-08 05:30 UTC, kolyanch commented on Lab2/Lab2Test/ExecutorRepositoryTest.cs
> +                executor.ExecutorId = 1;
Данная логика должна быть не в тесте, а в методе репозитория. Тест сократить до 
```C#
executorRepository.RemoveAllExecutors();
var executorId = executorRepository.AddExecutor(executor);
Assert.Equal(1, executorId);
executorRepository.RemoveExecutor(executorId);
```

2022-05-08 05:30 UTC, kolyanch commented on Lab2/Lab2Test/ExecutorRepositoryTest.cs
> +            {
Проверка наличия объекта с существующим идентификатором также должна быть в методе репозитория.

2022-05-08 17:33 UTC, kolyanch approved these changes

2022-05-08 17:33 UTC, closed without merging