Order accounting system. Server
itsec-labs/dotnet-2 pull request #7
Opened 2022-05-09 07:02 UTC by Victorina13

Чекушкина Вика 6312

2022-05-09 09:17 UTC, kolyanch requested changes

2022-05-09 09:17 UTC, kolyanch commented on src/Lab2/Lab2/Repository/OrderRepository.cs
> +                        ToDictionary<KeyValuePair<string, int>, string, int>(pair => pair.Key, pair => pair.Value);
Переписать по принципу:
```C#
return (from order in _orders
	from product in order.Products
	where ...
	group ... by ...
	into productGroup
	orderby ... descending 
	select ...)
	.ToDictionary(...);

```

Добавить тесты для этого метода

2022-05-09 09:17 UTC, kolyanch commented on src/Lab2/Lab2/Services/TimedHostedService.cs
> +        private int executionCount = 0;
Нарушение правил именования приватных полей. Ненужная инициализация

2022-05-09 09:17 UTC, kolyanch commented on src/Lab2/Lab2/Services/TimedHostedService.cs
> +        private void DoWork(object? state)
Убрать ?

2022-05-09 09:17 UTC, kolyanch commented on src/Lab2/Lab2/Repository/IOrderRepository.cs
> +        float GetAllCostOrder(Order order);
Зачем данный метод в интерфейсе?

2022-05-09 09:17 UTC, kolyanch commented on src/Lab2/ServerTests/CustomerRepositoryTests.cs
> +
Удалить пустоты в коде

2022-05-09 09:17 UTC, kolyanch commented on src/Lab2/ServerTests/OrderRepositoryTests.cs
> +        private Order CreateOrder(DateTime Data)
Сделать метод статичным. Нарушение правил именования аргументов методов

2022-05-09 09:17 UTC, kolyanch commented on src/Lab2/ServerTests/OrderRepositoryTests.cs
> +            DateTime Data = DateTime.Now;
Нарушение правил именования приватных переменных. И так во всех фактах в данном классе

2022-05-09 10:45 UTC, Victorina13 commented on src/Lab2/Lab2/Repository/IOrderRepository.cs
> +        float GetAllCostOrder(Order order);
Потому что я использую репозиторий под ссылкой интерфейса, и если их не будет в описании интерфейсе, я не смогу их использовать

2022-05-09 10:45 UTC, Victorina13 commented on src/Lab2/Lab2/Repository/OrderRepository.cs
> +            if (num < 0 || num > order.Products.Count)
Решила сделать так, что Id продукта - его номер в списке, для этого "изменена" нумерация.

2022-05-09 10:46 UTC, Victorina13 commented on src/Lab2/Lab2/Repository/OrderRepository.cs
> +            return null;
Если придёт num == order.Products.Count, то после декремента он станет (order.Products.Count-1) и в строке 158 не возникнет исключений из-за того, что оно гарантированно строго меньше Count.

2022-05-09 18:34 UTC, kolyanch commented on src/Lab2/Lab2/Repository/OrderRepository.cs
> +            return null;
Почему бы весь код этого метода не написать как:
```C#
GetOrder(id).Products[num - 1];
```
ArgumentOutOfRangeException кидается из коробки, ничего проверять не надо. Аналогично в других методах

2022-05-09 18:37 UTC, kolyanch commented on src/Lab2/Lab2/Repository/IOrderRepository.cs
> +        float GetAllCostOrder(Order order);
Я про конкретный метод GetAllCostOrder. Он у вас используется только внутри реализации репозитория и спокойно может быть удален из интерфейса

2022-05-10 05:10 UTC, kolyanch requested changes

2022-05-10 05:10 UTC, kolyanch commented on src/Lab2/Lab2/Exceptions/NotFoundException.cs
> +namespace Lab2.Exeptions
Опечатка в namespace

2022-05-10 05:10 UTC, kolyanch commented on src/Lab2/Lab2/Lab2.csproj
> +    <DocumentationFile>C:\Users\iru\source\repos\dotnet-2\src\Lab2\Lab2\Lab2.xml</DocumentationFile>
У меня нет такого пути, сделать пустой путь. Добавить:
<NoWarn>1701;1702;1591</NoWarn>

Это нужно, чтобы компилятор не выводил предупреждения о незадокументированных классах и методах

2022-05-10 05:10 UTC, kolyanch commented on src/Lab2/ServerTests/CustomerRepositoryTests.cs
> +        private Customer CreateCustomer(string phone)
Сделать метод статичным

2022-05-10 07:47 UTC, kolyanch requested changes
После исправлений сделать code cleanup

2022-05-10 07:47 UTC, kolyanch commented on src/Lab2/Lab2/Controllers/OrderController.cs
> +        [HttpGet("products per month")]
Такой маршрут недопустим

2022-05-10 07:47 UTC, kolyanch commented on src/Lab2/Lab2/Controllers/OrderController.cs
> +        [HttpGet("total cost")]
Такой маршрут недопустим

2022-05-11 05:39 UTC, kolyanch approved these changes

2022-05-11 05:39 UTC, closed without merging