Telegram Bot Server.
itsec-labs/dotnet-2 pull request #9
Opened 2022-05-09 12:57 UTC by putilove

Путилов Глеб 6312

2022-05-09 18:13 UTC, kolyanch requested changes

2022-05-10 06:51 UTC, putilove commented on src/Server/Server/Model/User.cs
> +            return nameHashCode ^ Id ^ Toggle.GetHashCode();
Могу ли я вычислять hash-код через свойство Id, не делая его иммутабельным, если мой код не подразумевает его изменения извне. Сразу после попадания в репозиторий User'a или UserEvent'а им присваивается Id, и он остаётся неизменным до конца.

2022-05-10 08:48 UTC, putilove commented on src/Server/Server/Model/User.cs
> +            return nameHashCode ^ Id ^ Toggle.GetHashCode();
`public void AddUser(User user)
        {
            if(_users.Exists(usr => usr.Equals(user)))
            {
                throw new AlreadyExistException();
            }
            user.Id = _users.Count == 0 ? 1 : _users.Max(evnt => evnt.Id) + 1;
            _users.Add(user);
        }`
        Но в таком случае придётся создавать здесь новый объект User'a  с необходимым Id((

2022-05-10 08:54 UTC, putilove commented on src/Server/Server/Model/User.cs
> +            return nameHashCode ^ Id ^ Toggle.GetHashCode();
Могу я это сделать?

2022-05-10 09:34 UTC, kolyanch commented
На данный момент солюшен не компилируется

2022-05-10 09:37 UTC, kolyanch commented on src/Server/Server/Model/User.cs
> +            return nameHashCode ^ Id ^ Toggle.GetHashCode();
Так и создавайте. Смысл иммутабельных объектов в том и состоит - любая операция над ним есть создание нового объекта

2022-05-10 12:08 UTC, kolyanch commented
20 ошибок компиляции в проекте с тестами

2022-05-10 13:28 UTC, putilove commented
теперь 0

2022-05-10 14:45 UTC, kolyanch requested changes

2022-05-10 14:45 UTC, kolyanch commented on src/Server/TgBot/Services/HandleUpdateService.cs
> +        var response = await client.PostAsync($"https://localhost:44349/api/User", new StringContent(JsonConvert.SerializeObject(user), Encoding.UTF8, "application/json"));
https://localhost:44349 должен быть определен в настройках (appsettings), хардкодить такое нельзя. Здесь и далее

2022-05-10 14:45 UTC, kolyanch commented on src/Server/TgBot/Services/HandleUpdateService.cs
> +                    string str = $"Success";
Зачем тут интерполирование? И зачем вообще эта переменная?
Здесь и далее, где встречается str

2022-05-10 14:45 UTC, kolyanch commented on src/Server/TgBot/Services/HandleUpdateService.cs
> +        HttpResponseMessage putResponse;
Совместить объявление и инициализацию (перенести объявление ниже)

2022-05-10 14:45 UTC, kolyanch commented on src/Server/TgBot/Services/HandleUpdateService.cs
> +public class HandleUpdateService
У всех методов в классе явно указать модификаторы доступа

2022-05-10 14:45 UTC, kolyanch commented on src/Server/TgBot/Services/HandleUpdateService.cs
> +        var response = await client.PostAsync($"https://localhost:443/send", new StringContent(JsonConvert.SerializeObject(userEvent), Encoding.UTF8, "application/json"));
Переменная response нигде не используется

2022-05-10 14:45 UTC, kolyanch commented on src/Server/TgBot/BotConfiguration.cs
> +    public string BotToken { get; init; }
Так как в проекте включен режим nullable, свойство должно быть объявлено как string?

2022-05-10 14:45 UTC, kolyanch commented on src/Server/TgBot/HostConfiguration.cs
> +        public string HostAddress { get; init; }
Так как в проекте включен режим nullable, свойство должно быть объявлено как string?

2022-05-10 16:34 UTC, kolyanch requested changes

2022-05-10 16:34 UTC, kolyanch commented on src/Server/TgBot/Services/HandleUpdateService.cs
> +    private static string? ServerAddress;
Нарушение правил именования приватных полей

2022-05-10 16:34 UTC, kolyanch commented on src/Server/TgBot/Services/HandleUpdateService.cs
> +
Убрать лишние строки

2022-05-10 16:34 UTC, kolyanch commented on src/Server/TgBot/Services/HandleUpdateService.cs
> +                var putResponse = await client.PutAsync(ServerAddress + $"/api/User/{user.Id}", new StringContent(JsonConvert.SerializeObject(user), Encoding.UTF8, "application/json"));
Не стоит совмещать конкатенацию и интерполирование. Внесите ServerAddress внутрь кавычек

2022-05-10 17:51 UTC, kolyanch requested changes

2022-05-10 17:51 UTC, kolyanch commented on src/Server/TgBot/Services/HandleUpdateService.cs
> +    private static string? s_serverAddress;
Почему такое странное название? Не исправлено

2022-05-10 17:51 UTC, kolyanch commented on src/Server/TgBot/Services/HandleUpdateService.cs
> +        var response = await client.PostAsync(s_serverAddress, new StringContent(JsonConvert.SerializeObject(user), Encoding.UTF8, "application/json"));
Вы уверены, что тут отправляет запрос на правильный адрес? Почему в Put маршрут /api/User/{user.Id}

2022-05-10 17:51 UTC, kolyanch commented on src/Server/TgBot/Services/HandleUpdateService.cs
> +        var response = await client.GetAsync($"s_serverAddress/api/User");
Этот запрос точно не сработает

2022-05-10 18:12 UTC, kolyanch approved these changes

2022-05-10 18:12 UTC, closed without merging